/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class affy_qualityControl_jniWrapper */

#ifndef _Included_affy_qualityControl_jniWrapper
#define _Included_affy_qualityControl_jniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     affy_qualityControl_jniWrapper
 * Method:    wlsAcc
 * Signature: ([D[D[DII)V
 */
JNIEXPORT void JNICALL Java_affy_qualityControl_jniWrapper_wlsAcc
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     affy_qualityControl_jniWrapper
 * Method:    seAcc
 * Signature: ([D[DII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_affy_qualityControl_jniWrapper_seAcc
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
