/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class affy_qualityControl_jniWrapper */

#ifndef _Included_affy_qualityControl_jniWrapper
#define _Included_affy_qualityControl_jniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     affy_qualityControl_jniWrapper
 * Method:    rlm_fit_anova
 * Signature: ([DII[D[D[DDI)V
 */
JNIEXPORT void JNICALL Java_affy_qualityControl_jniWrapper_rlm_1fit_1anova
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint);

/*
 * Class:     affy_qualityControl_jniWrapper
 * Method:    rlm_compute_se_anova
 * Signature: (II[D[D[D[DD)V
 */
JNIEXPORT void JNICALL Java_affy_qualityControl_jniWrapper_rlm_1compute_1se_1anova
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
